### ISSUE TITLE
URL for src_prefixes should end on /

### ISSUE THREAD

**Issue by sjcjonker** [cablelabs/dis-arbor-monitor#9]
On our version of Arbor the URL for src_prefixes must end on / so, as per [line 138](https://github.com/cablelabs/dis-arbor-monitor/blob/921bf3abc9726f7e0182287f8f305c8c3a8259a3/arbor-monitor/__main__.py#L138)
should read: (i.e. the **/** after src_prefixes):
```
    response = requests.get(f"{args.arbor_api_prefix}/api/sp/v6/alerts/{attack_id}/traffic/src_prefixes/"
                            f"?query_unit=bps&query_limit={prefix_query_limit}&query_view=network",
                            verify=not args.arbor_api_insecure,
                            headers={"X-Arbux-APIToken":args.arbor_api_token})
```
otherwise arbor gives an 400 series error.

**Comment by craigpratt** [comment]
This was a simple enough fix that I'm merging it to master without a PR. 

Issue fixed on master with commit 7e92e72c394
